modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="cubecraft"
version="1.0.0"
displayName="CubeCraft Cubelet Test"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tessa, MCreator"

[[dependencies.cubecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




